name: my_ecommerce
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  custom_navigation_bar: ^0.8.2
  flutter_image_slideshow: ^0.1.5
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.18.1
  get_it: ^7.5.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  connectivity_plus: ^3.0.6
  equatable: ^2.0.5
  dio: ^5.1.1
  dartz: ^0.10.1
  geolocator: ^9.0.2
  shimmer: ^2.0.0
  banner_carousel: ^1.2.1
  flutter_rating_bar: ^4.0.1
  share_plus: ^6.3.4
  get: ^4.6.5
  font_awesome_flutter: ^10.4.0
  custom_text: ^0.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.2.0
  flutter_typeahead: ^4.3.8
  google_maps_flutter: ^2.2.6
  cool_alert: ^2.0.1
  shared_preferences: ^2.1.0
  sizer: ^2.0.15
  flutter_svg: ^2.0.5
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  animations: ^2.0.7
  extended_wrap: ^0.1.5
  fluttertoast: ^8.2.2
  easy_stepper: ^0.6.0
  readmore: ^2.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
